GET http://localhost:8080/toppings/personal
Accept: application/json

###
GET http://localhost:8080/toppings/stats
Accept: application/json

###
POST http://localhost:8080/customers
Content-Type: application/json

{
  "email": "user3@asds.com",
  "toppings": [
    "Cheese",
    "Ham"
  ]
}


